channels:
  - defaults
  - conda-forge
dependencies:
  - black >=20.8b1 # for code formatting
  - jupyter  # for Notebooks
  - pytest  # for testing and performance analysis
  - sphinx >=1.4  # for documentation
  - sphinx_rtd_theme >=0.5.1  # for documentation
